# Generated by Django 4.0.4 on 2022-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='field_of_study',
            field=models.CharField(max_length=50),
        ),
    ]
