# Generated by Django 4.0.4 on 2022-05-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
